name: Terraform Provision and Ansible Patch

on:
  push:
    branches:
      - main

jobs:
  terraform:
    name: Run Terraform
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      
    - name: Set up Terraform
      uses: hashicorp/setup-terraform@v1
      with:
        terraform_version: 0.15.0
      
    - name: Terraform Init
      run: terraform init
      
    - name: Terraform Plan
      run: terraform plan -out=tfplan
      
    - name: Terraform Apply
      if: github.event_name == 'push' && github.ref == 'refs/heads/main'
      run: terraform apply -auto-approve tfplan
      id: terraform_apply
      continue-on-error: true
  
  ansible:
    name: Run Ansible
    runs-on: ubuntu-latest
    
    needs: terraform
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Capture Terraform Outputs
      if: ${{ needs.terraform.result == 'success' }}
      id: terraform_outputs
      run: |
        INSTANCE_ID=$(terraform output -raw instance_id)
        PUBLIC_IP=$(terraform output -raw public_ip)
        PRIVATE_IP=$(terraform output -raw private_ip)
        echo "::set-output name=instance_id::$INSTANCE_ID"
        echo "::set-output name=public_ip::$PUBLIC_IP"
        echo "::set-output name=private_ip::$PRIVATE_IP"
      
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'
        
    - name: Install Ansible
      run: |
        python3 -m pip install --upgrade pip
        pip3 install ansible
      
    - name: Run Ansible Playbook
      if: success()
      run: ansible-playbook -i ${{ steps.terraform_outputs.outputs.public_ip }}, playbook.yml
      env:
        ANSIBLE_HOST_KEY_CHECKING: False
