name: Terraform and Ansible Workflow

on:
  push:
    branches:
      - main

jobs:
  terraform:
    name: Run Terraform
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      
    - name: Set up Terraform
      uses: hashicorp/setup-terraform@v1
      with:
        terraform_version: 0.15.0
      
    - name: Terraform Init
      run: terraform init
      
    - name: Terraform Plan
      run: terraform plan -out=tfplan
      
    - name: Terraform Apply
      if: github.event_name == 'push' && github.ref == 'refs/heads/main'
      run: terraform apply -auto-approve tfplan
  
  ansible:
    name: Run Ansible
    runs-on: ubuntu-latest
    
    needs: terraform
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'
        
    - name: Install Ansible
      run: |
        python3 -m pip install --upgrade pip
        pip3 install ansible
      
    - name: Run Ansible Playbook
      run: ansible-playbook playbook.yml
